[theme]

# Primary accent for interactive elements
primaryColor = '#BB8FCE'

# Background color for the main content area
backgroundColor = '#5D6D7E'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FGHJGG'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
